"""Generate the cross-implementation test vectors.

The Python and Dart verifiers must agree, and "we ran both and they looked the
same" is not a test. This writes a fixture set that *both* suites read:

    dart/ftr_verify/test/vectors/encoding.json   canonical CBOR: accept + reject
    dart/ftr_verify/test/vectors/chain/          a real sealed chain
    dart/ftr_verify/test/vectors/tampered/       the same chain, attacked

Each side decodes, re-encodes and must reproduce the recorded bytes and digest.
Round-tripping through two independently written encoders is what makes the digest
worth putting on a §63 certificate.

    python core/tools/gen_vectors.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "core"))
sys.path.insert(0, str(ROOT / "core" / "tests"))

from factory import SimulatedHardwareKeystore, sample_ftr   # noqa: E402
from ftr.canonical_cbor import dumps                        # noqa: E402
from ftr.chain import Chain                                 # noqa: E402
from ftr.record import SealedRecord, seal                   # noqa: E402

OUT = ROOT / "dart" / "ftr_verify" / "test" / "vectors"

# Structures chosen to exercise every rule of the profile: shortest-form integers,
# key ordering across types and lengths, nesting, empty containers, bytes, and the
# shapes an FTR actually contains.
ACCEPT = [
    ("zero", 0),
    ("one-byte boundary", 23),
    ("two-byte boundary", 24),
    ("uint8 max", 255),
    ("uint16", 256),
    ("negative one", -1),
    ("negative boundary", -24),
    ("negative two-byte", -25),
    ("large sequence number", 4294967296),
    ("empty text", ""),
    ("ascii text", "IETF"),
    ("utf8 text", "Bhāratīya Sākṣya Adhiniyam"),
    ("empty bytes", b""),
    ("digest-shaped bytes", bytes(range(32))),
    ("empty array", []),
    ("int array", [1, 2, 3]),
    ("empty map", {}),
    ("single-entry map", {"a": 1}),
    ("key ordering: length before content", {"aa": 3, "b": 2, "a": 1}),
    ("key ordering: ints sort before text", {"a": 1, 1: 2, 10: 3}),
    ("booleans and null", {"t": True, "f": False, "n": None}),
    ("nested record shape", {
        "schema_version": 1,
        "prev_record_hash": b"\x00" * 32,
        "colorimetry": {"lab_x100": [2840, 1210, -960], "residual_x1000": 1420,
                        "gate_passed": True},
        "omitted": ["kit.lot"],
        "classification": {"prediction_set": ["opiate_class", "amphetamine_class"],
                           "label": None, "alpha_x1000": 50},
    }),
]

# Every one of these is a way a challenger could try to smuggle a second encoding
# of the same content past a verifier. Both implementations must refuse all of them.
REJECT = [
    ("0 in two bytes", "1800", "shortest-form violated"),
    ("1 in three bytes", "190001", "shortest-form violated"),
    ("indefinite-length map", "bf616101ff", "streaming form is not canonical"),
    ("indefinite-length bytes", "5f42010243030405ff", "streaming form is not canonical"),
    ("map keys out of order", "a2616201616101", "keys must sort bytewise on encoded bytes"),
    ("duplicate map key", "a2616101616101", "duplicate key"),
    ("half-float", "f97e00", "floats are not permitted in an FTR"),
    ("single-float", "fa47c35000", "floats are not permitted in an FTR"),
    ("double-float", "fb3ff199999999999a", "floats are not permitted in an FTR"),
    ("tagged value", "c11a514b67b0", "tags are not permitted"),
    ("trailing bytes", "0101", "more than one top-level item"),
    ("truncated array", "8301", "declares 3 items, carries 1"),
    ("undefined simple", "f7", "undefined is not permitted"),
]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    cases = []
    for name, value in ACCEPT:
        blob = dumps(value)
        cases.append({
            "name": name,
            "hex": blob.hex(),
            "sha256": hashlib.sha256(blob).hexdigest(),
        })

    (OUT / "encoding.json").write_text(json.dumps({
        "note": "Generated by core/tools/gen_vectors.py. Both the Python and Dart "
                "suites read this file. Decode each hex, re-encode it, and the bytes "
                "and digest must come back identical — in both implementations.",
        "profile": "RFC 8949 section 4.2.1 core deterministic rules, no floats, no tags",
        "accept": cases,
        "reject": [{"name": n, "hex": h, "why": w} for n, h, w in REJECT],
    }, indent=2) + "\n")

    # A real chain, sealed with a simulated hardware key.
    chain_dir = OUT / "chain"
    if chain_dir.exists():
        shutil.rmtree(chain_dir)
    chain = Chain(chain_dir)
    ks = SimulatedHardwareKeystore(OUT / ".vector-key.pem")
    labels = ["opiate_class", "negative", "amphetamine_class"]
    for i, label in enumerate(labels):
        f = sample_ftr(label)
        f.record_uuid = f"00000000-0000-4000-8000-{i:012d}"   # stable across runs
        if label == "amphetamine_class":
            f.location_bundle["corroboration_channels_agreeing"] = 2
            f.location_bundle["spoof_indicators"] = ["serving cell conflicts with fix by 310 km"]
        chain.append(seal(f, chain.head(), chain.next_sequence(), ks))
    chain.anchor(0)

    # The same chain, attacked. Each directory is one row of the adversary matrix.
    tampered = OUT / "tampered"
    if tampered.exists():
        shutil.rmtree(tampered)

    def copy_chain(name: str) -> Path:
        d = tampered / name
        shutil.copytree(chain_dir, d)
        return d

    # row 3 — rewrite the stored result, keep the old signature
    d = copy_chain("rewritten_result")
    p = d / "000000.ftr"
    rec = SealedRecord.from_envelope(p.read_bytes())
    body = rec.body
    body["classification"]["label"] = "negative"
    p.write_bytes(dumps({"v": 1, "body": dumps(body), "sig": rec.signature,
                         "pub": rec.public_key_der, "att": rec.attestation}))

    # row 5 — delete a record from the middle
    d = copy_chain("deleted_middle")
    (d / "000001.ftr").unlink()

    # reordering
    d = copy_chain("reordered")
    a, b = (d / "000000.ftr").read_bytes(), (d / "000001.ftr").read_bytes()
    (d / "000000.ftr").write_bytes(b)
    (d / "000001.ftr").write_bytes(a)

    (OUT / ".vector-key.pem").unlink(missing_ok=True)

    manifest = {
        "note": "Generated by core/tools/gen_vectors.py. The chain must verify in "
                "both implementations; every directory under tampered/ must fail in "
                "both, for the reason named.",
        "chain": {"records": len(labels), "anchored_to": 0, "must_verify": True},
        "tampered": {
            "rewritten_result": "signature no longer covers the body",
            "deleted_middle": "chain replay finds a gap",
            "reordered": "sequence and prev_record_hash disagree",
        },
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"wrote {len(cases)} accept + {len(REJECT)} reject vectors")
    print(f"wrote a {len(labels)}-record chain and {len(manifest['tampered'])} attacks")
    print(f"  -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
